spring:
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: rest-ruleta
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8100
